env:
  es6: true
  mocha: true
  node: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
      MemberExpression: 1
  linebreak-style:
    - error
    - unix
  no-cond-assign: off
  no-console: off
  no-unused-vars:
    - error
    - args: all
      argsIgnorePattern: ^_
      varsIgnorePattern: ^_
  no-var:
    - error
  quotes:
    - error
    - single
    - avoidEscape: true
  semi:
    - error
    - always
